# Generated by Django 4.2.5 on 2024-01-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('organization_name', models.CharField(max_length=70)),
                ('technology', models.CharField(max_length=50)),
            ],
        ),
    ]
